### ISSUE TITLE
Orthographic View of Segmented Image

### ISSUE THREAD

**Issue by akshaykulkarni07** [akshaykvnit/autonomous-delivery-robot#14]
Orthographic view of each segmented image is required for local planning to find the free routes. Since camera is fixed to the bot (height from ground is also fixed), it's rotation and translation w.r.t ground will also be fixed (assuming flat ground i.e. no slope). Then, we can use a perspective transform to get the orthographic view. Tasks: 

- [x] Get R and T matrices (pose) by placing an AprilTag on the ground.
- [x] Apply perspective transform using the inverse of the homography matrix on video (to check output).

Update: The outputs obtained currently seem to be fine. So, not doing the estimation of R and T from multiple images to get a better homography matrix.

Some outputs can be seen [here](https://drive.google.com/open?id=1yVhx6XpI4_MDnmvWq6Wegx87EJYVhhzZ). Output can be improved by getting a better estimate of the homography matrix (will be done soon).

@aj161198 Add your ideas about possibility of SLAM/stitching and other things in this thread (and correct any statements mentioned above if necessary).

**Comment by patilunmesh** [comment]
@aj161198
