### ISSUE TITLE
code optimization or translation

### ISSUE THREAD

**Issue by patilunmesh** [akshaykvnit/autonomous-delivery-robot#21]
Kindly go through the python scripts and post what can be done.

**Comment by patilunmesh** [comment]
I think we are done with optimization but what about translation? are we going to do it or not? @akshaykvnit

**Comment by akshaykulkarni07** [comment]
@patilunmesh Translation to what? C++? Or numba or something?

**Comment by patilunmesh** [comment]
Translation to cpp. but I don't think we need to do it. Now that I have tested the code.

**Comment by navidpanchi** [comment]
I'm learning numba, after that maybe we can profile the code and see if there is a need of optimization for any function.
