### ISSUE TITLE
Combine 2D LIDAR, cameras, and depth map data

### ISSUE THREAD

**Issue by akshaykulkarni07** [akshaykvnit/autonomous-delivery-robot#7]
Combine all vision sensors data to get a 360 degree depth map which can be used for local planning.

**Comment by aj161198** [comment]
I have finished stitching images without feature matching. This is done for two cameras as my laptop can support at max 2 cameras. Also calibration of all lab cameras is done as well as the algorithm for more than two cameras is designed but it is yet to be tested on a more powerful computer.

**Comment by patilunmesh** [comment]
I have combined contour of the segmented mask and lidar data, to get a 360 degree ring of obstacles

**Comment by patilunmesh** [comment]
Can we combine depthimage and segmented mask so that the lidar data and image point data will work well. @akshaykvnit  @aj161198
