### ISSUE TITLE
Selection of Electric Hardware

### ISSUE THREAD

**Issue by akshaykulkarni07** [akshaykvnit/autonomous-delivery-robot#8]
According to the motors recommended in this [document](https://docs.google.com/document/d/16N26uaJxUv-EnOp9eYT-tlRJwYzUAimSdRvTLGJnV3M/edit?usp=drivesdk), this is some analysis on those.

The [servo motor mentioned](https://robokits.co.in/motors/rc-servo-motors/high-torque-digital-waterproof-servo-motor-180deg-20kgcm?gclid=CjwKCAiAwZTuBRAYEiwAcr67OTtCpAjxtcrVFrQmToD3clpmxlcI-T5e3yizFOA04qF40idAXuuWIxoCsPYQAvD_BwE) has an input voltage range of 6 to 8.4 V. So, I don't think it will work at 5V. Since other devices will need 5V, our buck converter module would be set at 5V, and we would need a 2nd buck converter for this servo (not a huge problem w.r.t. cost if we use LM2596, but it will take up space). Also, current rating is not given for the servo, so that needs to be found out (because output rating of LM2596 buck conv is 3A, which is a common buck conv module, but we can get something else if required).

And [the BLDC mentioned](https://robu.in/product/emax-black-rs2306-2400kv-bldc-fpv-racing-motor/?gclid=CjwKCAiAwZTuBRAYEiwAcr67OdLsaSlSAzf0I1kwaD4VIOldrvxTuHf4CwAit8crtmdWqpp9LN98bhoC0BgQAvD_BwE) can run only on 3S or 4S batteries (11.1V or 14.8V), so we can choose the battery using this constraint of 3S/4S and the mAh rating. So, mAh requirement calculation is done or pending (I think we had done some part of it in the previous meeting)? This BLDC has a maximum current draw (as per it's datasheet which mentions it's current draw w.r.t. input voltage and which propeller is used) of around 40 A. So, the [FlipSky VESC](https://m.banggood.in/FLIPSKY-FSESC-50A-SK8-ESC-Electronic-Speed-Control-5V-BEC-for-Electric-Longboard-RC-Car-E-bike-p-1293459.html?gmcCountry=IN&currency=INR&cur_warehouse=CN&createTmp=1&utm_source=googleshopping&utm_medium=cpc_bgs&utm_content=lijing&utm_campaign=ssc-ing-all-newcustom-1-0822&gclid=Cj0KCQjwgNXtBRC6ARIsAIPP7RtYiTwxSaRyEWDT6iRkaD23m6e6FpyMt4AyAs28jwpAw24QxVK_W40aAnHLEALw_wcB) (50A rating) will do. This VESC also gives a 5V/1.5A port, so that's useful.

Add any other suggestions for hardware in this issue itself.

**Comment by patilunmesh** [comment]
Servo motor works well with 5V. Instead of BLDC we used simple DC motor directly connected to 6s lipo battery and L298N motor driver
